project_id = "gialzvvswxadxolnwots"

[functions.generate-side-character]
verify_jwt = false

[functions.generate-side-character-avatar]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.generate-scene-image]
verify_jwt = false

[functions.extract-memory-events]
verify_jwt = false

[functions.extract-character-updates]
verify_jwt = false
